### ISSUE TITLE
feat(dependencies): would it be possible to upgrade this to Angular 4.x.x?

### ISSUE THREAD

**Issue by GiuseppePiscopo** [unsafecode/ng2-aot#2]
In my team we're trying to put together a working AOT build with angular 4, @ngtools/webpack (not full angular-cli) and lazy loaded modules. Mini repo is available [here](https://github.com/BrainCrumbz/ngtools-webpack-demo).

[Current version](https://github.com/BrainCrumbz/ngtools-webpack-demo/tree/64590091726b59452fa0ade2bf2a724ed9a196db) excludes JiT-related entry points and uses AoT entry points. Build goes fine, but at runtime we see the dreaded `Error: Cannot find module '../private/module.ngfactory'.` when trying to browse to lazy loaded area.

Locally we also tried doing the opposite (as you do in this repo): exclude AoT-related stuff and use JiT entry points. Same as before: build ok, error at runtime. We also tried adding `"baseUrl": "."` to tsconfig, but it made no difference.

In both cases, as noted on other angular-cli issues (e.g. [2452](https://github.com/angular/angular-cli/issues/2452)), in build output folder we see `0-bundle.js.map`, but not `0-bundle.js`.

Have you tried upgrading this project to angular 4.1.1, @ngtools/webpack 1.3.1, webpack 2.2.1 (or newer), typescript 2.2.1 (or newer)? Thanks

**Comment by unsafecode** [comment]
@GiuseppePiscopo I'll try to find some time and do all the fixing.

**Comment by IAMtheIAM** [comment]
Yes would you make this update to latest? 

Update: Actually I got it working. Only a few changed needed. [PR submitted](https://github.com/unsafecode/ng2-aot/pull/3)
I also added the missing '/lazy/lazy-feature' route
